### ISSUE TITLE
something unrelated  but can you please help

### ISSUE THREAD

**Issue by amitpande74** [Superzchen/iLearnPlus#14]
Hi,
I have tried all the possible solutions from google to install PyQt5.
```
(base) amit@amit-X705UDR:~$ /home/amit/miniconda3/bin/python
Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from ilearnplus import runiLearnPlus
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amit/.local/lib/python3.8/site-packages/ilearnplus/__init__.py", line 5, in <module>
    from .iLearnPlusBasic import *
  File "/home/amit/.local/lib/python3.8/site-packages/ilearnplus/iLearnPlusBasic.py", line 7, in <module>
    from PyQt5.QtWidgets import (QApplication, QWidget, QPushButton, QFileDialog, QLabel, QHBoxLayout, QGroupBox, QTextEdit,
ModuleNotFoundError: No module named 'PyQt5'

```
Kindly suggest.

**Comment by Superzchen** [comment]
Hi, 
iLearnPlus is a GUI-based program, please make sure your system support graphical interfaces.

**Comment by amitpande74** [comment]
Dear Author,
I have Ubuntu 22.04. I ran this command to check -
```
sudo lshw -c video
[sudo] password for amit: 
  *-display                 
       description: VGA compatible controller
       product: UHD Graphics 620
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 07
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=1920,1080
       resources: irq:141 memory:ed000000-edffffff memory:c0000000-cfffffff ioport:f000(size=64) memory:c0000-dffff
  *-display
       description: 3D controller
       product: GP107M [GeForce GTX 1050 Mobile]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:140 memory:ee000000-eeffffff memory:d0000000-dfffffff memory:e0000000-e1ffffff ioport:e000(size=128) memory:ef000000-ef07ffff

```
Regards.

**Comment by amitpande74** [comment]
Thanks for your support! 
I installed PyQt5 using this page ([](https://gist.github.com/ujjwal96/1dcd57542bdaf3c9d1b0dd526ccd44ff))
It worked.

**Comment by amitpande74** [comment]
I installed PyQt5 using this resource [](https://gist.github.com/ujjwal96/1dcd57542bdaf3c9d1b0dd526ccd44ff)
It worked.
Regards.

**Comment by amitpande74** [comment]
[https://gist.github.com/ujjwal96/1dcd57542bdaf3c9d1b0dd526ccd44ff](url)
This worked.
Thanks.
Regards.
